Repository pengchenyu111/HuangShan-Server, pull requests merged in 2020-02, with the labels that each got.

#2 改善接口为Restful风格
  log/firestorm.log
  src/main/java/cn/hfut/huangshan/controller/AdminController.java
  src/main/java/cn/hfut/huangshan/controller/DailyNumController.java
  src/main/java/cn/hfut/huangshan/controller/HourlyNumController.java
  src/main/java/cn/hfut/huangshan/controller/LoginController.java
  src/main/java/cn/hfut/huangshan/controller/TouristController.java
  src/main/resources/application.yml
Labels: enhancement

#6 完成一些基础数据的查询
  log/firestorm.log
  src/main/java/cn/hfut/huangshan/controller/RoleController.java
  src/main/java/cn/hfut/huangshan/controller/ScenicController.java
  src/main/java/cn/hfut/huangshan/controller/ScenicManageController.java
  src/main/java/cn/hfut/huangshan/mapper/RoleMapper.java
  src/main/java/cn/hfut/huangshan/mapper/ScenicManageMapper.java
  src/main/java/cn/hfut/huangshan/mapper/ScenicMapper.java
  src/main/java/cn/hfut/huangshan/pojo/Role.java
  src/main/java/cn/hfut/huangshan/pojo/Scenic.java
  src/main/java/cn/hfut/huangshan/pojo/ScenicManage.java
  src/main/java/cn/hfut/huangshan/service/RoleService.java
  src/main/java/cn/hfut/huangshan/service/ScenicManageService.java
  src/main/java/cn/hfut/huangshan/service/ScenicService.java
  src/main/resources/mapper/RoleMapper.xml
  src/main/resources/mapper/ScenicManageMapper.xml
  src/main/resources/mapper/ScenicMapper.xml
Labels: enhancement

#9 修复了登录中的bug和暂时关闭了拦截器
  log/firestorm.log
  src/main/java/cn/hfut/huangshan/config/WebAppConfig.java
  src/main/java/cn/hfut/huangshan/constants/ErrorCode.java
  src/main/java/cn/hfut/huangshan/controller/LoginController.java
  src/main/java/cn/hfut/huangshan/controller/NotificationController.java
  src/main/java/cn/hfut/huangshan/mapper/NotificationMapper.java
  src/main/java/cn/hfut/huangshan/pojo/Notification.java
  src/main/java/cn/hfut/huangshan/service/NotificationService.java
  src/main/java/cn/hfut/huangshan/service/TouristService.java
  src/main/java/cn/hfut/huangshan/utils/ResponseUtil.java
  src/main/resources/mapper/NotificationMapper.xml
Labels: bug

#10 改进景点管理
  log/firestorm.log
  src/main/java/cn/hfut/huangshan/pojo/ScenicManage.java
  src/main/resources/mapper/ScenicManageMapper.xml
Labels: improve

#11 完成查询某个管理员管理的所有地点
  log/firestorm.log
  src/main/java/cn/hfut/huangshan/controller/ScenicManageController.java
  src/main/java/cn/hfut/huangshan/mapper/ScenicManageMapper.java
  src/main/java/cn/hfut/huangshan/pojo/AdminScenicManage.java
  src/main/java/cn/hfut/huangshan/service/ScenicManageService.java
  src/main/resources/mapper/ScenicManageMapper.xml
Labels: enhancement

#12 完成管理员个人信息的更新
  log/firestorm.log
  src/main/java/cn/hfut/huangshan/controller/AdminController.java
  src/main/java/cn/hfut/huangshan/mapper/AdminMapper.java
  src/main/java/cn/hfut/huangshan/service/AdminService.java
  src/main/resources/mapper/AdminMapper.xml
Labels: enhancement

#14 改善了id生成的问题和完成的notification的所有接口
  log/firestorm.log
  src/main/java/cn/hfut/huangshan/controller/NotificationController.java
  src/main/java/cn/hfut/huangshan/controller/ScenicManageController.java
  src/main/java/cn/hfut/huangshan/mapper/NotificationMapper.java
  src/main/java/cn/hfut/huangshan/mapper/ScenicManageMapper.java
  src/main/java/cn/hfut/huangshan/pojo/Admin.java
  src/main/java/cn/hfut/huangshan/pojo/AdminScenicManage.java
  src/main/java/cn/hfut/huangshan/pojo/Notification.java
  src/main/java/cn/hfut/huangshan/pojo/Role.java
  src/main/java/cn/hfut/huangshan/pojo/Scenic.java
  src/main/java/cn/hfut/huangshan/pojo/ScenicManage.java
  src/main/java/cn/hfut/huangshan/pojo/Tourist.java
  src/main/java/cn/hfut/huangshan/service/NotificationService.java
  src/main/java/cn/hfut/huangshan/service/ScenicManageService.java
  src/main/java/cn/hfut/huangshan/utils/IdWorker.java
  src/main/resources/mapper/NotificationMapper.xml
  src/main/resources/mapper/ScenicManageMapper.xml
Labels: bug, enhancement

#15 基本上完成了notification的所有接口以及修复了一些bug
  log/firestorm.log
  src/main/java/cn/hfut/huangshan/controller/NotificationController.java
  src/main/java/cn/hfut/huangshan/mapper/NotificationMapper.java
  src/main/java/cn/hfut/huangshan/service/NotificationService.java
  src/main/resources/mapper/NotificationMapper.xml
Labels: enhancement

#16 Login fix
  log/firestorm.log
  src/main/java/cn/hfut/huangshan/constants/ErrorCode.java
  src/main/java/cn/hfut/huangshan/controller/LoginController.java
  src/main/java/cn/hfut/huangshan/pojo/Admin.java
Labels: enhancement

#17 完成了所有用户投诉的接口的编写及测试
  log/firestorm.log
  src/main/java/cn/hfut/huangshan/controller/ComplaintController.java
  src/main/java/cn/hfut/huangshan/mapper/ComplaintMapper.java
  src/main/java/cn/hfut/huangshan/pojo/Complaint.java
  src/main/java/cn/hfut/huangshan/service/ComplaintService.java
  src/main/java/cn/hfut/huangshan/utils/IdWorker.java
  src/main/resources/mapper/ComplaintMapper.xml
  src/main/resources/mapper/NotificationMapper.xml
Labels: enhancement

#18 添加了2个投诉的接口
  log/firestorm.log
  src/main/java/cn/hfut/huangshan/controller/ComplaintController.java
  src/main/java/cn/hfut/huangshan/mapper/ComplaintMapper.java
  src/main/java/cn/hfut/huangshan/pojo/Complaint.java
  src/main/java/cn/hfut/huangshan/service/ComplaintService.java
  src/main/resources/mapper/ComplaintMapper.xml
Labels: enhancement
